# Generated by Django 2.1.11 on 2020-01-09 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviegeeks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_id',
            field=models.CharField(max_length=16, primary_key=True, serialize=False, unique=True),
        ),
    ]
